### PR TITLE
Fix: Prevent updating game library entries during library update when no data has changed. Fixes #2384

### LINKED ISSUE #2384: Prevent Playnite from updating game database file when new data is not different on library update
**Describe the bug**
Updating a library will cause Playnite to update all game database files, even when the new data has no changes from the current data.

Currently, it has been confirmed that the `IsInstalled` property is updated everytime even when there is no change.

**To Reproduce**
Update any game library.

### PR DESCRIPTION
**Pull request by darklinkpower**
Fix: Prevent updating game library entries during library update when no data has changed. Fixes #2384

I have verified that:
- [x] These changes work, by building the application and testing them.
- [x] Pull request is targeting `devel` branch.
- [x] I added myself into [contributors file](https://github.com/JosefNemec/Playnite/blob/devel/source/Playnite.DesktopApp/Resources/contributors.txt) if I want to receive contribution credit in the application itself.

### CODE REVIEW

File: source/Playnite/Database/GameDatabase.cs [hunk 1]
```diff
@@ -1059,34 +1059,60 @@ public List<Game> ImportGames(LibraryPlugin library, bool forcePlayTimeSync, ILi
...
-                        existingGame.IsInstalled = newGame.IsInstalled;
-                        existingGame.InstallDirectory = newGame.InstallDirectory;
+                        var existingGameUpdated = false;
+                        if (existingGame.IsInstalled != newGame.IsInstalled)
+                        {
+                            existingGame.IsInstalled = newGame.IsInstalled;
+                            existingGameUpdated = true;
+                        }
+                        
+                        if (existingGame.InstallDirectory.Equals(newGame.InstallDirectory, StringComparison.OrdinalIgnoreCase) == false)
```
Comment (JosefNemec) [inline source/Playnite/Database/GameDatabase.cs:1069]: This will throw if `InstallDirectory` is null.

File: source/Playnite/Database/GameDatabase.cs [hunk 2]
```diff
@@ -1059,34 +1059,60 @@ public List<Game> ImportGames(LibraryPlugin library, bool forcePlayTimeSync, ILi
...
+                        {
+                            existingGame.InstallDirectory = newGame.InstallDirectory;
+                            existingGameUpdated = true;
+                        }
+                        
                         if (existingGame.PlayAction == null || existingGame.PlayAction.IsHandledByPlugin)
                         {
-                            existingGame.PlayAction = newGame.PlayAction;
+                            if (existingGame.PlayAction != newGame.PlayAction)
```
Comment (JosefNemec) [inline source/Playnite/Database/GameDatabase.cs:1077]: GameAction object doesn't implement != operator, so this check will not work and always will be false.

File: source/Playnite/Database/GameDatabase.cs (hunk 1 above)
Comment (darklinkpower) [reply source/Playnite/Database/GameDatabase.cs]: Fixed by using `string.Equals` method instead.

**Comment by darklinkpower** [comment]
Only remaining issue is the check of the `PlayAction` but as discussed on discord will be ignored for now since they are handled differently in Playnite 9.
